name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have updated to the [latest version of this workflow](./releases/latest).
          required: true
        - label: I am using Alfred 5 or later.
          required: true
  - type: input
    id: alfred-version-info
    attributes:
      label: Alfred version
      description: Open the `Alfred Preferences.app`, go to the `General` tab. The version number is shown at the top left.
      placeholder: 5.5 [2251]
    validations: { required: true }
  - type: input
    id: macos-version-info
    attributes:
      label: macOS version
      description: Click on the  symbol in the menu bar and select `About This Mac`.
      placeholder: Sonoma 14.3
    validations: { required: true }
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations: { required: true }
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If applicable, add screenshots or a screen recording to help explain your problem.
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the problem
      placeholder: |
        For example:
        1. Open Alfred.
        2. Run the keyword…
        3. Select…
    validations: { required: true }
  - type: textarea
    id: debugging-log
    attributes:
      label: Debugging Log
      description: You can get a debugging log by opening the workflow in Alfred preferences and pressing `⌘ + D`. A small window will open up which will log everything happening during the execution of the Workflow. Use the malfunctioning part of the workflow once more, copy the content of the log window, and paste it here. If the debugging log is long, please attach it as file instead of pasting everything in here.
      render: Text
    validations: { required: true }
  - type: textarea
    id: workflow-configuration
    attributes:
      label: Workflow Configuration
      description: Please add a screenshot of your [workflow configuration](https://www.alfredapp.com/help/workflows/user-configuration/).
    validations: { required: true }
